language: node_js
node_js:
  - "7"
script: npm run build
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
before_deploy:
  - "sed -i '/public/d' .gitignore"
  - "git add .gitignore public -f"
  - "rm -r node_modules"
deploy:
  provider: azure_web_apps
  site: html5-battleship
  skip_cleanup: true