language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp-cli
script: npm run build
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
before_deploy:
  - "sed -i '/public/d' .gitignore"
  - "git add public -f"
  - "rm -r node_modules"
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  site: html5-battleship